sex("Nikolaj_Timofeev", m).
sex("Elena_Kulagina", f).
sex("Daniil_Kulagin", m).
sex("Aleksej_Timofeev", m).
sex("Lidiya_Timofeeva", f).
sex("Matvej_Timofeev", m).
sex("Nikolaj_Kulagin", m).
sex("Lidiya_Sokolova", f).
sex("Aleksandr_Gromov", m).
sex("Aleksej_Kulagin", m).
sex("Aleksandr_Kulagin", m).
sex("Larisa_Kulagina", f).
sex("Elizaveta_Kulagina", f).
sex("Aleksandr_Kulagin", m).
sex("Darya_Kulagina", f).
sex("Aleksandr_Sokolov", m).
sex("Praskovya_Sokolova", f).
sex("Vladimir_Timofeev", m).
sex("Zinaida_Vintovkina", f).
sex("Vasilij_Kurov", m).
sex("Pelageya_Gromova", f).
sex("Evgenij_Timofeev", m).
sex("Valeriya_Kurova", f).
sex("Dmitrij_Timofeev", m).
sex("Elena_Skripkina", f).
sex("Nikita_Timofeev", m).
sex("Liza_Nikulina", f).
sex("Dmitrij_Kurov", m).
sex("Alisa_Palyonova", f).
sex("Daniil_Kurov", m).
sex("Vasilisa_Petruhina", f).
sex("Nikolaj_Skripkina", m).
sex("Lidiya_Blistunova", f).
sex("Ivan_Kurov", m).
sex("Daniil_Kurov", m).
sex("Aleksandra_Kirilenko", f).
sex("Anna_SHCHeglova", f).
sex("Aleksej_SHCHeglov", m).
sex("Larisa_SHCHeglova", f).
sex("Nikolaj_Vintovkin", m).
sex("Aleksej_Vintovkin", m).
sex("Mariya_Kazakova", f).
sex("Valerij_Vintovkin", m).
sex("Darya_Kuznecova", f).
sex("Mihail_Kazakov", m).
sex("Valeriya_Fedorenko", f).
sex("Arina_Kiselyova", f).
sex("Artyom_Kiselyov", m).
sex("Natalya_Pushkin", f).
sex("Andrej_Kiselyov", m).
sex("Anastasiya_Pavlova", f).
sex("Nikolaj_Pushkin", m).
sex("Elena_Rezvyakova", f).
sex("Mihail_Kurov", m).
sex("Alina_Nikulina", f).
sex("Dmitrij_Petruhin", m).
sex("Alina_Nikitina", f).
sex("Pavel_Palyonov", m).
sex("Andrej_Palyonov", m).
sex("Anna_Smirnova", f).
sex("Veronika_YAgodka", f).
sex("Maksim_YAgodkin", m).
sex("Ekaterina_Mamaeva", f).
sex("Dmitrij_Gromov", m).
sex("Nikita_Gromov", m).
sex("Elena_Sapihanova", f).
sex("Matvej_Gromov", m).
sex("Anastasiya_Sanchenko", f).
sex("Ravil_Sapihanov", m).
sex("Dzhennet_Rozyeva", f).
sex("Elena_Korobkina", f).
sex("Ilya_Korobkin", m).
sex("Tatyana_Karpuhina", f).
sex("Ivan_Korobkin", m).
sex("Galina_Minenko", f).
sex("Semyon_Karpuhin", m).
sex("Anastasiya_Konon", f).
sex("Mihail_Kulagin", m).
sex("Polina_Tatarina", f).
parent("Nikolaj_Timofeev", "Daniil_Kulagin").
parent("Elena_Kulagina", "Daniil_Kulagin").
parent("Nikolaj_Timofeev", "Matvej_Timofeev").
parent("Elena_Kulagina", "Matvej_Timofeev").
parent("Aleksej_Timofeev", "Aleksandr_Gromov").
parent("Lidiya_Timofeeva", "Aleksandr_Gromov").
parent("Aleksej_Timofeev", "Nikolaj_Timofeev").
parent("Lidiya_Timofeeva", "Nikolaj_Timofeev").
parent("Nikolaj_Kulagin", "Aleksej_Kulagin").
parent("Lidiya_Sokolova", "Aleksej_Kulagin").
parent("Nikolaj_Kulagin", "Elena_Kulagina").
parent("Lidiya_Sokolova", "Elena_Kulagina").
parent("Aleksej_Kulagin", "Aleksandr_Kulagin").
parent("Larisa_Kulagina", "Aleksandr_Kulagin").
parent("Aleksej_Kulagin", "Elizaveta_Kulagina").
parent("Larisa_Kulagina", "Elizaveta_Kulagina").
parent("Aleksandr_Kulagin", "Nikolaj_Kulagin").
parent("Darya_Kulagina", "Nikolaj_Kulagin").
parent("Aleksandr_Sokolov", "Lidiya_Sokolova").
parent("Praskovya_Sokolova", "Lidiya_Sokolova").
parent("Vladimir_Timofeev", "Aleksej_Timofeev").
parent("Zinaida_Vintovkina", "Aleksej_Timofeev").
parent("Vasilij_Kurov", "Lidiya_Timofeeva").
parent("Pelageya_Gromova", "Lidiya_Timofeeva").
parent("Evgenij_Timofeev", "Vladimir_Timofeev").
parent("Valeriya_Kurova", "Vladimir_Timofeev").
parent("Dmitrij_Timofeev", "Evgenij_Timofeev").
parent("Elena_Skripkina", "Evgenij_Timofeev").
parent("Nikita_Timofeev", "Dmitrij_Timofeev").
parent("Liza_Nikulina", "Dmitrij_Timofeev").
parent("Dmitrij_Kurov", "Vasilij_Kurov").
parent("Alisa_Palyonova", "Vasilij_Kurov").
parent("Daniil_Kurov", "Dmitrij_Kurov").
parent("Vasilisa_Petruhina", "Dmitrij_Kurov").
parent("Nikolaj_Skripkina", "Elena_Skripkina").
parent("Lidiya_Blistunova", "Elena_Skripkina").
parent("Ivan_Kurov", "Valeriya_Kurova").
parent("Anna_SHCHeglova", "Valeriya_Kurova").
parent("Daniil_Kurov", "Ivan_Kurov").
parent("Aleksandra_Kirilenko", "Ivan_Kurov").
parent("Aleksej_SHCHeglov", "Anna_SHCHeglova").
parent("Larisa_SHCHeglova", "Anna_SHCHeglova").
parent("Nikolaj_Vintovkin", "Zinaida_Vintovkina").
parent("Arina_Kiselyova", "Zinaida_Vintovkina").
parent("Aleksej_Vintovkin", "Nikolaj_Vintovkin").
parent("Mariya_Kazakova", "Nikolaj_Vintovkin").
parent("Valerij_Vintovkin", "Aleksej_Vintovkin").
parent("Darya_Kuznecova", "Aleksej_Vintovkin").
parent("Mihail_Kazakov", "Mariya_Kazakova").
parent("Valeriya_Fedorenko", "Mariya_Kazakova").
parent("Artyom_Kiselyov", "Arina_Kiselyova").
parent("Natalya_Pushkin", "Arina_Kiselyova").
parent("Andrej_Kiselyov", "Artyom_Kiselyov").
parent("Anastasiya_Pavlova", "Artyom_Kiselyov").
parent("Nikolaj_Pushkin", "Natalya_Pushkin").
parent("Elena_Rezvyakova", "Natalya_Pushkin").
parent("Mihail_Kurov", "Daniil_Kurov").
parent("Alina_Nikulina", "Daniil_Kurov").
parent("Dmitrij_Petruhin", "Vasilisa_Petruhina").
parent("Alina_Nikitina", "Vasilisa_Petruhina").
parent("Pavel_Palyonov", "Alisa_Palyonova").
parent("Veronika_YAgodka", "Alisa_Palyonova").
parent("Andrej_Palyonov", "Pavel_Palyonov").
parent("Anna_Smirnova", "Pavel_Palyonov").
parent("Maksim_YAgodkin", "Veronika_YAgodka").
parent("Ekaterina_Mamaeva", "Veronika_YAgodka").
parent("Dmitrij_Gromov", "Pelageya_Gromova").
parent("Elena_Korobkina", "Pelageya_Gromova").
parent("Nikita_Gromov", "Dmitrij_Gromov").
parent("Elena_Sapihanova", "Dmitrij_Gromov").
parent("Matvej_Gromov", "Nikita_Gromov").
parent("Anastasiya_Sanchenko", "Nikita_Gromov").
parent("Ravil_Sapihanov", "Elena_Sapihanova").
parent("Dzhennet_Rozyeva", "Elena_Sapihanova").
parent("Ilya_Korobkin", "Elena_Korobkina").
parent("Tatyana_Karpuhina", "Elena_Korobkina").
parent("Ivan_Korobkin", "Ilya_Korobkin").
parent("Galina_Minenko", "Ilya_Korobkin").
parent("Semyon_Karpuhin", "Tatyana_Karpuhina").
parent("Anastasiya_Konon", "Tatyana_Karpuhina").
